version: "3.9"

services:
  auth-postgres:
    image: postgres:16-alpine
    container_name: auth-postgres
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  subscription-postgres:
    image: postgres:16-alpine
    container_name: subscription-postgres
    environment:
      POSTGRES_USER: subscription_user
      POSTGRES_PASSWORD: subscription_password
      POSTGRES_DB: subscription_db
    ports:
      - "5433:5432"   
    volumes:
      - billing_postgres_data:/var/lib/postgresql/data

  billing-postgres:
    image: postgres:16-alpine
    container_name: billing-postgres
    environment:
      POSTGRES_USER: billing_user
      POSTGRES_PASSWORD: billing_password
      POSTGRES_DB: billing_db
    ports:
      - "5434:5432"
    volumes:
      - billing_postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./docker/prometheus:/etc/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
      - loki
      - tempo
    environment:
      - GF_LOG_LEVEL=info
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-simple-json-datasource
    ports:
      - "3001:3000"  # Grafana UI
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./docker/loki:/etc/loki

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./docker/promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yaml

  tempo:
    image: grafana/tempo:2.4.1
    container_name: tempo
    command: ["-config.file=/etc/tempo.yml"]
    volumes:
      - ./docker/tempo/tempo.yml:/etc/tempo.yml
      - tempo_data:/var/tempo
    ports:
      - "3200:3200"   
      - "4317:4317"   
      - "4318:4318"   


  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.96.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./docker/otel/otel-collector-config.yml:/etc/otel-collector-config.yml
      - otel_data:/var/otel
    ports:
      - "43180:4318"   
      - "43170:4317"   
    depends_on:
      - tempo

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092, PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      CLUSTER_ID: LshexmLSRjiD-5Z2hMkvbQ

    volumes:
      - kafka_data:/var/lib/kafka/data

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.1
    container_name: schema-registry-saas
    depends_on:
      - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:29092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:9094
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
    ports:
      - "9094:9094"

  
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-saas
    ports:
      - "8090:8090"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  redis:
    image: redis:7
    container_name: redis-saas
    ports:
      - "6379:6379"

  liquibase_postgres:
    image: liquibase/liquibase:4.27
    container_name: liquibase-saas
    depends_on:
      - billing-postgres
    environment:
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://billing-postgres:5432/billing_db
      LIQUIBASE_COMMAND_USERNAME: billing_user
      LIQUIBASE_COMMAND_PASSWORD: billing_password
    volumes:
      - ./docker/postgres:/liquibase/changelog
    working_dir: /liquibase/changelog
    entrypoint: [ "liquibase" ]
    command:
      - "--changeLogFile=changelog-master.yaml"
      - "update"
      - "--log-level=debug"

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma
    ports:
      - "8000:8000"
    volumes:
      - ./chroma-data:/data

  airflow:
    image: apache/airflow:2.7.3
    container_name: airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: 'some_fernet_key_here'
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    ports:
      - "8001:8001"

  
  mlflow:
    image: cr.fly.dev/mlflow/mlflow:2.7.0
    container_name: mlflow
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow-data:/mlflow

volumes:
  postgres_data:
  subscription_postgres_data:
  billing_postgres_data:
  grafana_data:
  kafka_data:
  tempo_data:
  otel_data:

